#!/bin/bash

# Runs a command on a remote system

GALAXY_DIR="${HOME}/galaxy"

if [ -z $1 ]; then
    echo "./gxcmd <ipaddr> [<cmd>]"
    exit 1
fi

# Get Hostname from connections file

CONN_LINE=$(cat $GALAXY_DIR/tmp/connections | grep $1)

HOSTNAME=$(echo $CONN_LINE | cut -d";" -f1)

if [ -z "$HOSTNAME" ]; then
    echo "Couldn't find hostname in connections. Was this computer mounted?"
    exit 1
fi

CMD="bash" # Command to run

if [ -n "$2" ]; then
    CMD=$2
fi

CURR_DIFF="${HOME}/galaxy/mnt/${HOSTNAME}"
DEST=$(echo $CONN_LINE | cut -d";" -f2)

DEST_DIR=$(pwd | sed 's,'"$CURR_DIFF"',,g')

ssh -t $DEST "cd $DEST_DIR; $CMD"