#!/bin/bash

# Creates the files in the home directory

mkdir "${HOME}/galaxy"

mkdir "${HOME}/galaxy/bin"
mkdir "${HOME}/galaxy/config"
mkdir "${HOME}/galaxy/mnt"
mkdir "${HOME}/galaxy/tmp"

mkdir "${HOME}/galaxy/tmp/mnt"

echo "" > "${HOME}/galaxy/tmp/connections"
echo "GALAXY_DIR=\"${HOME}/galaxy\"" > "${HOME}/.gxrc"
echo "DEFAULT_XPRA=\":100\"" >> "${HOME}/.gxrc"