#!/bin/bash

# Mounts a remote system

source "${HOME}/.gxrc"

set -e

if [ -z $1 ]; then
    echo "./gxmount <ipaddr>"
    exit 1
fi

HOSTNAME=$(ssh $1 -o PasswordAuthentication=no hostname)

if [ -z $HOSTNAME ]; then
    echo "SSH Connection Failed. Make sure that you have permission to log into this computer, and that you have ssh keys set up!"
    exit 1
fi

# Mount the filesystem

MNT_ID=$(uuidgen)

if [ ! -d "$GALAXY_DIR/tmp/mnt/$MNT_ID" ]; then
    mkdir $GALAXY_DIR/tmp/mnt/$MNT_ID
fi

sshfs $1:/ $GALAXY_DIR/tmp/mnt/$MNT_ID &

_pid=$! # Save the sshfs PID, since sometimes it gets stuck

ln -s $GALAXY_DIR/tmp/mnt/$MNT_ID $GALAXY_DIR/mnt/$HOSTNAME

REMOTE_GX_DIR="$GALAXY_DIR/mnt/$HOSTNAME/home/$USER" # TODO Make this properly handle custom home paths

echo "$HOSTNAME;$1;$MNT_ID;$_pid;$REMOTE_GX_DIR" >> $GALAXY_DIR/tmp/connections