#!/bin/bash

# Mounts a remote system

source "${HOME}/.gxrc"

INFO_CMD="gxtarget-info"

if [ -z $1 ]; then
    echo "./gxmount <ipaddr>"
    exit 1
fi

INFO_STR=$(ssh $1 -o PasswordAuthentication=no "bash -c $INFO_CMD")

if [ -z $INFO_STR ]; then
    echo "Mounting Failed. Make sure that you have permission to log into this computer, and that you have ssh keys set up! Also make sure that galaxy scripts are installed and that '$INFO_CMD' is in the home directory"
    exit 1
fi

set -e

HOSTNAME=$(echo $INFO_STR | cut -d";" -f1)

REMOTE_GX_DIR=$(echo $INFO_STR | cut -d";" -f3)

# Mount the filesystem

MNT_ID=$(uuidgen)

if [ ! -d "$GALAXY_DIR/tmp/mnt/$MNT_ID" ]; then
    mkdir $GALAXY_DIR/tmp/mnt/$MNT_ID
fi

sshfs $1:/ $GALAXY_DIR/tmp/mnt/$MNT_ID &

_pid=$! # Save the sshfs PID, since sometimes it gets stuck

ln -s $GALAXY_DIR/tmp/mnt/$MNT_ID $GALAXY_DIR/mnt/$HOSTNAME

echo "$HOSTNAME;$1;$MNT_ID;$_pid;$REMOTE_GX_DIR" >> $GALAXY_DIR/tmp/connections