#!/bin/bash

# Runs a program through ssh and sets the environment variables correctly. This is run on the host machine.

source "${HOME}/.gxrc"

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "gxrunner-host <ip_addr> <command_name>"
    exit 1
fi

# Get Hostname from connections file

CONN_LINE=$(cat $GALAXY_DIR/tmp/connections | grep $1)

HOSTNAME=$(echo $CONN_LINE | cut -d";" -f1)
IP=$(echo $CONN_LINE | cut -d";" -f2)

REMOTE_GX=$(echo $CONN_LINE | cut -d";" -f5) # Remote Galaxy Dir

if [ -z "$HOSTNAME" ]; then
    echo "Couldn't find hostname in connections. Was this computer mounted?"
    exit 1
fi

cat "$GALAXY_DIR/mnt/$HOSTNAME$REMOTE_GX/config/commands"

CMD_LINE=$(cat $GALAXY_DIR/mnt/$HOSTNAME$REMOTE_GX/config/commands | grep $2)

if [ -z "$CMD_LINE" ]; then
    echo "Command not found on this system"
    exit 1
fi

CMD=$(echo $CMD_LINE | cut -d";" -f2)

USE_XPRA=$(echo $CMD_LINE | cut -d";" -f3)

USE_VNC=$(echo $CMD_LINE | cut -d";" -f4)

RUN_IN_TMUX=""

if [ -n $USE_XPRA ] || [ -n $USE_VNC ]; then 
    RUN_IN_TMUX="1"
fi

DISPLAY_NUM=":0"

if [ -n $USE_XPRA ]; then 
    DISPLAY_NUM=$DEFAULT_XPRA
fi

ssh $IP "bash -c \"source .profile && gxrunner-target $CMD\""

if [ -n $USE_XPRA ]; then
    
fi