#!/bin/bash

# Runs a program through ssh and sets the environment variables correctly. This is run on the host machine.

GALAXY_DIR="${HOME}/galaxy"

if [ -z "$1" ]; then
    echo "gxrunner-host <command_name>"
    exit 1
fi

CMD_LINE=$(cat $GALAXY_DIR/config/commands | grep $1)

if [ -z "$CMD_LINE" ]; then
    echo "Command not found on this system"
    exit 1
fi

CMD=$(echo $CMD_LINE | cut -d";" -f2)

USE_XPRA=$(echo $CMD_LINE | cut -d";" -f3)

USE_VNC=$(echo $CMD_LINE | cut -d";" -f4)

RUN_IN_TMUX=""

if [ -n $USE_XPRA ] || [ -n $USE_VNC ]; then 
    RUN_IN_TMUX="1"
fi

DISPLAY_NUM=":0"

if [ -n $USE_XPRA ]; then 
    DISPLAY_NUM=$(xpra list | grep LIVE | cut -d":" -f2)
    if [ -z "$DISPLAY_NUM"]; then
        echo "Starting Xpra at :100..."
        xpra start :100
        DISPLAY_NUM=":100"
    fi
fi