#!/bin/bash

# Runs a program through ssh and sets the environment variables correctly. This is run on the target machine.

GALAXY_DIR="${HOME}/galaxy"
DEFAULT_XPRA=":100"

if [ -z "$1" ]; then
    echo "gxrunner-target <command_name>"
    exit 1
fi

CMD_LINE=$(cat $GALAXY_DIR/config/commands | grep $1)

if [ -z "$CMD_LINE" ]; then
    echo "Command not found on this system"
    exit 1
fi

CMD=$(echo $CMD_LINE | cut -d";" -f2)

USE_XPRA=$(echo $CMD_LINE | cut -d";" -f3)

USE_VNC=$(echo $CMD_LINE | cut -d";" -f4)

RUN_IN_TMUX=""

if [ -n $USE_XPRA ] || [ -n $USE_VNC ]; then 
    RUN_IN_TMUX="1"
fi

DISPLAY_NUM=":0"

if [ -n $USE_XPRA ]; then 
    DISPLAY_NUM=$(xpra list | grep LIVE | cut -d":" -f2)
    if [ -z "$DISPLAY_NUM"]; then
        echo "Starting Xpra at $DEFAULT_XPRA..."
        xpra start $DEFAULT_XPRA
        DISPLAY_NUM="$DEFAULT_XPRA"
    fi
fi

export DISPLAY=:$DISPLAY_NUM

if [ -n $RUN_IN_TMUX ]; then
    TMUX_SESS_NAME=$(uuidgen)
    tmux new -d -s gx_"$TMUX_SESS_NAME" "$1"
fi